name: CI
on:
  push:
    branches:
    - 'github-action-ci'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - run: |
          df -h
          echo ====
          free -h
          echo ====
          swapon
          echo ====
          mount
          echo ====
          ls -l /
          sudo du -xh -d1 --exclude=/usr --exclude=/var /
          #echo ====
          #ls -l /var
          #sudo du -xh -d1 /var
          echo ====
          ls -l /mnt
          sudo du -xh -d1 /mnt
