name: CI
on:
  push:
    branches:
    - 'github-action-ci'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - run: |
          df -h
          echo ====
          free -h
          echo ====
          mount
          echo ====
          ls -l /
          du -sh /*
          echo ====
          ls -l /var
          du -sh /var/*
          echo ====
          ls -l /mnt
          du -sh /mnt/*
